# Generated by Django 3.1.7 on 2021-04-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img_url',
            field=models.CharField(default='http://https://i.stack.imgur.com/y9DpT.jpg', max_length=500),
        ),
    ]
